### ISSUE TITLE
Contribute link should be removed from Header

### ISSUE THREAD

**Issue by anselmbradford** [smcgov/SMC-Connect#10]
I think the "Contribute" link should be removed from the header. During the fellowship, SMC-Connect was the reference implementation for the Ohana API, but now it needs to focus on serving its purpose–servicing SMC, so one less button in the header is a good idea. The language in Contribute can be added to the About section or the footer along with the "get this app for your city" link (https://github.com/smcgov/SMC-Connect/issues/9)

**Comment by monfresh** [comment]
This was already done back in 2014.
