### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by amymariejoh** [smcgov/SMC-Connect#242]
Hello - our organization rebranded and changed our name and we would like to have our profile updated.  We were formerly Bayshore Christian Ministries (bayshore.org) and are now Hope Horizon East Palo Alto (hopehorizonepa.org).  Please use our new information and see our website for any other updates.

FYI - Signing up for Github seems to be the only way to give feedback as an organization, which was a pain to sign up for for this purpose.  It seems there should be a simpler way for orgs in San Mateo County to let you all know if there is out of date information on the page or to request to be included.

Thanks,
Amy

**Comment by monfresh** [comment]
Hi Amy. Thanks for your feedback. I will work with HSA to update their feedback page. In the meantime, there is an admin interface for SMC-Connect that allows organizations like yours to update their information. If you still have a bayshore.org email address, you can sign up here with that email: https://admin.smc-connect.org/

Once you sign up and sign in, you should be able to see all entries that match bayshore.org, and you can update the information.

If no one in your organization has access to a @bayshore.org email, let me know and I can update the website to hopehorizonepa.org, and then you should be able to create an admin account with your @hopehorizonepa.org email address.

**Comment by amymariejoh** [comment]
Thanks - I was able to create a login but the profile hasn't been updated fully and now when I login it doesn't show any organizations.

Amy

[cid:ce5b6cf6-488d-4822-932d-3f7013775668]
Amy Joh
Director of Partner Engagement
Hope Horizon East Palo Alto
(Formerly Bayshore Christian Ministries)

Please note my new email - ***@***.***

hopehorizonepa.org
1001 Beech Street
East Palo Alto, CA 94303
650.327.1139 main line
650.327.9943 direct

________________________________

**Comment by amymariejoh** [comment]
PS the updated email used for login is ***@***.*** if helpful.

[cid:9592e879-4e97-4022-808d-2dfdc4bb129f]
Amy Joh
Director of Partner Engagement
Hope Horizon East Palo Alto
(Formerly Bayshore Christian Ministries)

Please note my new email - ***@***.***

hopehorizonepa.org
1001 Beech Street
East Palo Alto, CA 94303
650.327.1139 main line
650.327.9943 direct

________________________________

**Comment by monfresh** [comment]
Hi Amy. I just added you as an admin for this location:

https://admin.smc-connect.org/locations/bayshore-christian-ministries

If you are signed in, you should be able to see and update the details for that location.
