### ISSUE TITLE
Need to update an address and service details for Project Ninety

### ISSUE THREAD

**Issue by caminarmktg** [smcgov/SMC-Connect#244]
Hello, 

I logged into [SMC-connect](https://admin.smc-connect.org/) as oer a previous thread and am able to access the Caminar listing, but I can't access the Project Ninety, a division of Camianr listing. Project Ninety no longer has its own email addresses, as they were merged with Caminar in 2017. Is it possible to allow me access to that listing? 

LIsting: https://www.smc-connect.org/locations/project-90?keyword=project+ninety&location=

P90 webpage on the Caminar website as FYI: https://www.caminar.org/p90

Thank you so much,
Wendy/ Caminar Marketing

**Comment by monfresh** [comment]
HI Wendy. I just updated the P90 listing's website to caminar.org/p90. As long as you have a @caminar.org email, you should now be able to access it.
