### ISSUE TITLE
Updating Information for Accessible Recreation in Redwood City

### ISSUE THREAD

**Issue by SUEParksandRec** [smcgov/SMC-Connect#250]
Could you change the following on your website?
ITEMs IN **bold** need changing
**Special Needs Afternoon Program**
[Redwood City Parks, Recreation and Community Services Department](https://www.smc-connect.org/locations?org_name=Redwood+City+Parks%2C+Recreation+and+Community+Services+Department)
Location Hours
Varies
General Contact Info
[www.redwoodcity.org](http://www.redwoodcity.org/)
**[swolk@redwoodcity.org](mailto:swolks@redwoodcity.org)**
(650) 780-7313 voice
(650) 364-5399 fax
Specific Contact
**Susan Wolk
Coordinator**
Physical Address
1455 Madison Avenue
Redwood City, CA 94061
Mailing Address
Special Needs Rec Program
1455 Madison Avenue
Redwood City, CA 94061
Offers activity programs such as trips, movies, swimming and social events for persons with physical limitations or developmental disabilities.
Description: **SNAP (Special Needs Afternoon Program) i**s a city-run program that provides recreational programming to teens and adults with mental, physical, emotional and/or developmental disabilities. Activities include dances, classes and special events.
Location
Public Transit: SAMTRANS stops within 2 blocks. Carpools or other transportation may possibly be arranged.

Services
Fees: Vary according to program. Sponsorships for some programs may be available. Cash and checks accepted.
Audience: Persons with physical limitations/disabilities or developmental disabilities
Eligibility: Physical limitation or disability, or developmental disability
How to Apply: Walk in, apply by phone, mail or email.
Service Wait Estimate: No wait.
Service Areas:
**Redwood City**
Cupertino
Los Altos
Mountain View
Palo Alto
San Mateo County
Sunnyvale

**Comment by monfresh** [comment]
Hi Susan. There is an admin interface for SMC-Connect where organizations can make updates themselves. You can sign up for an account on the site below, using the same email address tied to the organization. In your case, swolk@redwoodcity.org

https://admin.smc-connect.org/

Once you sign in, you should automatically have access to all listings for your organization. The way it determines which listings you have access to is by comparing the domain name of your email address with the one in the listing.

Let me know if you have any issues or questions.

**Comment by SUEParksandRec** [comment]
I'm new to this position, so I was unable to log in.  I'm not sure who the account is with but I can find out.

**Comment by monfresh** [comment]
You need to create an account first before logging in. Anyone can sign up. Here is the link: https://admin.smc-connect.org/sign_up

**Comment by SUEParksandRec** [comment]
I'm on it, thank you!

**Comment by SUEParksandRec** [comment]
It does not allow me to confirm my account for whatever reason.  I presume it is because I am new to the city job.

**Comment by monfresh** [comment]
How long you've been at this job has no bearing on your ability to use admin.smc-connect.org

Can you please tell me step by step what you did and at what point it failed, and what the exact error message was? If you can, please attach a screenshot. Thanks!

**Comment by SUEParksandRec** [comment]
***@***.***
It doesn't ever send the confirmation, so I can't get past this screen.

Sue

**Comment by SUEParksandRec** [comment]
***@***.***

**Comment by monfresh** [comment]
If you didn't receive a confirmation email, please check your spam/junk folders. If you don't see it there, please ask your IT department if they are blocking it. The emails come from "mtcastro@smcgov.org" and include [SMC-Connect Admin] as part of the subject.

**Comment by SUEParksandRec** [comment]
I'm all set, thank you!
