### ISSUE TITLE
Please remove listing

### ISSUE THREAD

**Issue by JRQ5826** [smcgov/SMC-Connect#252]
Menlo Park Library is showing a listing for a service that is not available. We will reach out when the service resumes at our location.
You can message me here, or directly at jrquinonez@menlopark.gov, if there are any concerns. Thank you.

Listing to be removed: https://www.smc-connect.org/locations/menlo-park-library/project-read-adult-literacy-program

**Comment by monfresh** [comment]
@JRQ5826 I updated the website to menlopark.gov instead of .org. If you sign back in to the admin site, you should now have access to all Menlo Park entries.

**Comment by JRQ5826** [comment]
Thank you for your help!

Juan-




[cid:CMP_Email_Logo_100dpi_05d92d5b-e8e3-498f-93a6-d0da509bd602111111111.png]

  Juan R. Quinonez
  Library Assistant III
  Menlo Park Library
  800 Alma St.
  tel  650-330-2507
  menlopark.gov<https://www.menlopark.gov/>
  *Note our emails have changed to @menlopark.gov
