### ISSUE TITLE
Updating account info for Seniors At Home/Jewish Family and Children's Services

### ISSUE THREAD

**Issue by amydilaura** [smcgov/SMC-Connect#255]
I need to update the inforamtion on this page (https://www.smc-connect.org/locations/jewish-family-and-children-s-services/seniors-at-home-2245-post-street) but I can't log in to it and the person who set it up is no longer with our organization. Can you please advise on how I can access the page to edit it? Thanks.

**Comment by monfresh** [comment]
Hi @amydilaura. If you have a seniorsathome.org email address, you can create an account with that email address here:

https://admin.smc-connect.org/sign_up

You'll get an email with a link to confirm your account, and then once you sign in, you should have access to that location.

**Comment by monfresh** [comment]
I'm assuming this issue has been resolved since I haven't heard back in over a year. If you're still having trouble updating the information, let me know.
