### ISSUE TITLE
Drive Forward Program - Peninsula Family Service

### ISSUE THREAD

**Issue by bcohn123** [smcgov/SMC-Connect#282]
Hi there - I was able to obtain access to the main PFS page to make edits, but I am not able to figure out how to access https://www.smc-connect.org/locations/peninsula-family-service/ways-to-work-vehicle-loan-program or why it is not connected to the main PFS page as a program. Are you able to a) help delete this or b) get me access to the page to make edits?

Thanks,
Bryan cohn
bcohn@pfso.org

**Comment by monfresh** [comment]
Hi Bryan,

The way the admin interface determines which listings you can have access to is by comparing the domain name of your email address (pfso.org <http://pfso.org/> in your case) with the details within each listing. Currently, most (if not all) Peninsula Family Service listings use the full www.peninsulafamilyservice.org <http://www.peninsulafamilyservice.org/> domain name. That means I need to manually add you as an admin for each listing you'd like to edit. Alternatively, I can find each PFS listing and update the website to pfso.org <http://pfso.org/>.

Having said that, I just visited pfso.org <http://pfso.org/> in my browser, and it automatically redirected to https://peninsulafamilyservice.org/. So it sounds like the canonical URL is the full one. 

In that case, if you have an email address that ends in peninsulafamilyservice.org <http://peninsulafamilyservice.org/>, then the easiest solution would be to create an account with that email address.

In the meantime, I've added you as an admin for the DriveForward Vehicle Loan Program.

Moncef
