### ISSUE TITLE
Update to Meals on Wheels Peninsula Volunteers INC

### ISSUE THREAD

**Issue by sdachauer** [smcgov/SMC-Connect#293]
Current Website: https://1pvi.org/mealsonwheels/

Current email: mealsonwheels@1pvi.org

no fax, please remove

Current Director: Stephanie Figeira - sfigeira@1pvi.org

Suggested Donation: $5.25 per meal, please remove information about $2 charge for folks 18-59

Audience: Senior citizens age 60 or over, disabled individuals age 18-59

Service Areas:
Atherton
Belmont
Burlingame
East Menlo Park
East Palo Alto
Foster City
Hillsborough
Menlo Park
Millbrae
Portola Valley
Redwood City
San Carlos
San Mateo
Woodside

*folks residing in the following cities should contact San Francisco Meals on Wheels for service (415-920-1111): San Bruno, Brisbane, South San Francisco, Daly City, Colma*

Thank you!

**Comment by monfresh** [comment]
Hello @sdachauer. I've updated the information. You can see the changes here: https://www.smc-connect.org/locations/peninsula-volunteers/meals-on-wheels-south-county

Now that the information has been updated, anyone with a 1pvi.org email address can create an admin account here:

https://admin.smc-connect.org/sign_up

Once you create the account and confirm your email address, you can sign in, and you will then be able to update any location tied to 1pvi.org.
