### ISSUE TITLE
Add smc-connect specific Google Maps API key

### ISSUE THREAD

**Issue by anselmbradford** [smcgov/SMC-Connect#58]
Implement https://github.com/codeforamerica/ohana-web-search/issues/582 and add smc-connect specific instructions for adding an API key if for some reason the map quota is surpassed. Probably not worth adding a key because it needs to be tied to an account (though it could be organized together with the Google Translate key), but the groundwork to just add a key and have it work should be in place.

**Comment by monfresh** [comment]
This was done a while ago.
