### ISSUE TITLE
SFMNP doesn't return results, Senior Farmers' Market Nutrition Program does

### ISSUE THREAD

**Issue by anselmbradford** [smcgov/SMC-Connect#62]
Search for `SFMNP`, don't get any results.
Search for `Senior Farmers' Market Nutrition Program`, get one result.

How would both of these return the same results? Add SFMNP **and its** synonyms to the list of keywords for a location I presume. Any option to automatically add the synonyms for this and other like it (such as WIC)?

**Comment by monfresh** [comment]
Neither keyword is returning a result now, but they both show the custom info box.
