### ISSUE TITLE
Update farmer's market partial to use accepted_payments field

### ISSUE THREAD

**Issue by anselmbradford** [smcgov/SMC-Connect#64]
If/when the API is updated to use the `accepted_payments` service field, the [farmer's market partial](https://github.com/smcgov/SMC-Connect/blob/master/app/views/component/locations/detail/_body.html.haml#L186-L189) should be updated with the accepted_payments partial that will be added to Ohana Web Search.

**Comment by monfresh** [comment]
This was already done a few years ago. Here's an example location where you can see the Payment methods accepted and Products sold: https://www.smc-connect.org/locations/coastside-farmers-market-of-pacifca?kind=Farmers%27+Markets
