### ISSUE TITLE
Unable to contact Court Ordered Work Program 

### ISSUE THREAD

**Issue by BlueC95** [smcgov/SMC-Connect#70]
I have a community service work assignment to finish, i paid to processing fee $35, and i was told that court work program will contact me for interview. But nobody had ever contacted me for interview, so i call the court work program to see what was going on, but the system asked me to leave a message with my name, court work number and other info, and they will reach me back. i called a thousand time and left a thousand messages, but never got a call back. The court work interview due day is now passed, but i still have no way to get interviewed and start the community service work assignment.
Does anyone know what should i do or who should i find now?

**Comment by echan650** [comment]
Hello BlueC95.  I'm not familiar with the program that you submitted about with the courts system.  I would encourage you to contact Bianca, Executive Assistant to the Court Executive Office at bfasuescu@sanmateocourt.org.
