### ISSUE TITLE
Add apple-icons

### ISSUE THREAD

**Issue by anselmbradford** [smcgov/SMC-Connect#8]
**Details**
“Touch icons” are the favicons of mobile devices and tablets. See [background reading](http://mathiasbynens.be/notes/touch-icons). These need to be created for this project.

**Skills / Resources required**
- Access to Adobe Photoshop or equivalent.

**To Fix**
Create an `apple-touch-icon-precomposed.png` file in /public/ per specs given in the [HTML5 Boilerplate project](https://github.com/h5bp/html5-boilerplate/pull/1425).

**Steps**
- [ ] Create an `apple-touch-icon-precomposed.png` using the SMC-Connect logo branding.
- [ ] Place in `/public/apple-touch-icon-precomposed.png`

**Comment by monfresh** [comment]
This was already done in #68. Thanks again, Ans!
